apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dvf5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0058-tenant/tkrw-pr712-0075-0058-app/devfile-sample-dvf5@sha256:548fd8e8e335afab5a43e92221333b35a97cc9088272f9a7f14e63ba36121b96
        name: my-nodejs
        resources: {}
status: {}
